config/routes.rb
Rails.application.routes.draw do

  root 'static_pages#home'
  get 'about', controller:  :static_pages
  get 'vcard/upload'

  resources :newsletters do
    get 'send_newsletter'
    post 'send_mail'
  end
  devise_for :users, controllers: {sessions: "usuario/sessions"}

  resources :contatos do
    get 'migrate'
    collection do
      post :mass_action
    end
    resources :notes, :only => [:edit, :create, :update, :index, :destroy]
  end
  resources :ajaxcontatos

  namespace :usuario do
    resources :generals
    resources :messages
    resources :roles
  end

  namespace :credit do
    resources :documents
    namespace :bank do
      resources :generals
    end
    namespace :client do
      resources :generals do
        get 'find_expired'
      end
      namespace :partner do
        resources :document_lists
      end
      namespace :warranty do
        resources :document_lists
      end
    end
  end

  namespace :business do
    resources :notes
    resources :histories
    resources :generals
    resources :internationals
    resources :nationals
    resources :sites
  end

  namespace :internationals do
    resources :generals
  end

  namespace :juridico do
    resources :andamentos
    resources :processos
  end

  namespace :product do
    resources :documents
    resources :generals
    resources :internationals
    resources :nationals
    namespace :thirdparty do
      resources :bases
    end
  end

end

app/models/business/note.rb
class Business::Note < ApplicationRecord
  belongs_to :general
end

app/models/credit/client/note.rb
class Credit::Client::Note < ApplicationRecord
  belongs_to :credit_client_general
  belongs_to :credit_bank_general, class_name: '::Credit::Bank::General'
  validates :date, format: {with: /^[0-9]{4}-(0[1-9]|1[0-2])-(0[1-9]|[1-2][0-9]|3[0-1])$/, multiline: true}
end

app/models/note.rb
class Note < ActiveRecord::Base
  belongs_to :contato
end

app/models/product/note.rb
class Product::Note < ApplicationRecord
  belongs_to :product_general, foreign_key: 'product_id'
end

app/controllers/business/notes_controller.rb
class Business::NotesController < ApplicationController
  before_action :set_business_note, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!

  # GET /business/notes
  # GET /business/notes.json
  def index
    @business_notes = Business::Note.all
  end

  # GET /business/notes/1
  # GET /business/notes/1.json
  def show
  end

  # GET /business/notes/new
  def new
    @business_note = Business::Note.new
  end

  # GET /business/notes/1/edit
  def edit
  end

  # POST /business/notes
  # POST /business/notes.json
  def create
    @business_note = Business::Note.new(business_note_params)

    respond_to do |format|
      if @business_note.save
        format.html { redirect_to @business_note, notice: 'Note was successfully created.' }
        format.json { render :show, status: :created, location: @business_note }
      else
        format.html { render :new }
        format.json { render json: @business_note.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /business/notes/1
  # PATCH/PUT /business/notes/1.json
  def update
    respond_to do |format|
      if @business_note.update(business_note_params)
        format.html { redirect_to @business_note, notice: 'Note was successfully updated.' }
        format.json { render :show, status: :ok, location: @business_note }
      else
        format.html { render :edit }
        format.json { render json: @business_note.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /business/notes/1
  # DELETE /business/notes/1.json
  def destroy
    @business_note.destroy
    respond_to do |format|
      format.html { redirect_to business_notes_url, notice: 'Note was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_business_note
      @business_note = Business::Note.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def business_note_params
      params.require(:business_note).permit(:note, :business_general_id)
    end
end

app/controllers/notes_controller.rb
class NotesController < ApplicationController
  before_action :set_note, only: [:show, :edit, :update, :destroy]

  # GET /notes
  # GET /notes.json
  def index
    @notes = Note.where(contato_id: params[:contato_id])
    @contato = Contato.find(params[:contato_id])
  end

  # GET /notes/1
  # GET /notes/1.json
  def show
  end

  # GET /notes/new
  def new
    @note = Note.new
  end

  # GET /notes/1/edit
  def edit
    #render plain: @note.to_json
  end

  # POST /notes
  # POST /notes.json
  def create
    @contato = Contato.find(params[:contato_id])
    @note = @contato.notes.create(note_params)

    redirect_to contato_path(@contato)
  end

  # PATCH/PUT /notes/1
  # PATCH/PUT /notes/1.json
  def update
    respond_to do |format|
      if @note.update(note_params)
        format.html { redirect_to @note.contato, notice: 'Note was successfully updated.' }
        format.json { render :show, status: :ok, location: @note }
      else
        format.html { render :edit }
        format.json { render json: @note.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /notes/1
  # DELETE /notes/1.json
  def destroy
    @contato = Contato.find(params[:contato_id])
    @note.destroy
    respond_to do |format|
      format.html { redirect_to contato_path(@contato), notice: 'Note was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_note
      @note = Note.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def note_params
      params.require(:note).permit(:observacao, :contato_id)
    end
end

app/helpers/business/notes_helper.rb
module Business::NotesHelper
end

app/helpers/notes_helper.rb
module NotesHelper
end

app/views/notes/_form.html.erb
<%= form_for  @note, url: contato_note_path, html: {class: 'form-horizontal'} do |f| %>


  <% if @note.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@note.errors.count, 'error') %> <%= I18n.t('cant_save', model: t('Note.model.Note'))%></h2>

      <ul>
      <% @note.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

    <div class="form-group">
      <%= f.label :contato_id, class: 'control-label'  %><br>
      <%= f.collection_select(:contato_id, Contato.order(:first_name).all, :id, :full_name,{:prompt => 'Please select the author of this post'}, ({ :class=> 'form-control', :disabled => 'disabled'}))  %>
    </div>
  <div class="form-group">
    <%= f.label :observacao, t('Contact.view.Add_Note'), class: 'control-label' %>
    <%= f.text_area :observacao, class: 'form-control' %>
  </div>

  <div class="actions form-group">
    <%= f.submit 'Editar Observação', class: 'btn btn-primary' %>
  </div>
<% end %>

app/views/notes/_index.html.erb
<% if !@notes.blank? %>
    <table class = "table table-striped">
      <thead>
      <tr>
        <th>Observação</th>
        <th colspan="2"></th>
      </tr>
      </thead>
      <tbody>
      <% @notes.each do |note| %>
          <tr>
            <td><%= note.observacao %></td>
            <td><%= link_to t('Edit'), edit_contato_note_path({id: note.id, contato_id: note.contato.id}) %></td>
            <td><%= link_to t('Destroy'), contato_note_path({id: note.id, contato_id: note.contato.id}) , method: :delete, data: { confirm: 'Are you sure?' }
            %></td>
          </tr>
      <% end %>
      </tbody>
    </table>
<% else %>
    <h5><%= I18n.t('Contact.view.no_registred', entitie: t('Contact.model.Note') ) %></h5>
<% end %>

app/views/notes/edit.html.erb
<h1><%= t('Edit_Note') %></h1>

<%= render 'form' %>

<%= link_to t('Show'), contato_note_path(:id=>@note.id,  :contato_id=>@note.contato_id) %> |
<%= link_to t('Back'), contato_notes_path %>

app/views/notes/index.html.erb
<p id="notice"><%= notice %></p>

<h1><%= t('Note.model.Notes') %></h1> <h3><%= @contato.full_name %></h3>

<%= render 'index' %>

app/views/notes/new.html.erb
<h1><%= t('Note.model.Add_Note') %></h1>

<%= render 'form' %>

<%= link_to t('Back'), contato_notes_path %>

app/views/notes/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong><%= t('Note.model.Note') %>:</strong>
  <%= @note.observacao %>
</p>

<p>
  <strong><%= t('Contact.model.Contact') %>:</strong>
  <%= @note.contato.full_name %>
</p>

<%= link_to t('Edit'), edit_contato_note_path(:id => @note.id,  :contato_id => @note.contato_id) %> |
<%= link_to t('Back'), contato_notes_path %>