config/routes.rb
Rails.application.routes.draw do

  root 'static_pages#home'
  get 'about', controller:  :static_pages
  get 'vcard/upload'

  resources :newsletters do
    get 'send_newsletter'
    post 'send_mail'
  end
  devise_for :users, controllers: {sessions: "usuario/sessions"}

  resources :contatos do
    get 'migrate'
    collection do
      post :mass_action
    end
    resources :notes, :only => [:edit, :create, :update, :index, :destroy]
  end
  resources :ajaxcontatos

  namespace :usuario do
    resources :generals
    resources :messages
    resources :roles
  end

  namespace :credit do
    resources :documents
    namespace :bank do
      resources :generals
    end
    namespace :client do
      resources :generals do
        get 'find_expired'
      end
      namespace :partner do
        resources :document_lists
      end
      namespace :warranty do
        resources :document_lists
      end
    end
  end

  namespace :business do
    resources :notes
    resources :histories
    resources :generals
    resources :internationals
    resources :nationals
    resources :sites
  end

  namespace :internationals do
    resources :generals
  end

  namespace :juridico do
    resources :andamentos
    resources :processos
  end

  namespace :product do
    resources :documents
    resources :generals
    resources :internationals
    resources :nationals
    namespace :thirdparty do
      resources :bases
    end
  end

end

app/models/newsletter.rb
class Newsletter < ActiveRecord::Base
  has_and_belongs_to_many :products

  def status_text
    I18n.t(status.to_s, :scope => 'newsletters.model.status')
  end
end

app/controllers/newsletters_controller.rb
class NewslettersController < ApplicationController
  before_action :set_newsletter, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!

  # GET /newsletters
  # GET /newsletters.json
  def index
    @newsletters = Newsletter.all
  end

  # GET /newsletters/1
  # GET /newsletters/1.json
  def show
  end

  # GET /newsletters/new
  def new
    @newsletter = Newsletter.new
  end

  # GET /newsletters/1/edit
  def edit
  end

  # POST /newsletters
  # POST /newsletters.json
  def create
    @newsletter = Newsletter.new(newsletter_params)

    respond_to do |format|
      if @newsletter.save
        format.html { redirect_to @newsletter, notice: 'Newsletter was successfully created.' }
        format.json { render :show, status: :created, location: @newsletter }
      else
        format.html { render :new }
        format.json { render json: @newsletter.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /newsletters/1
  # PATCH/PUT /newsletters/1.json
  def update
    respond_to do |format|
      if @newsletter.update(newsletter_params)
        format.html { redirect_to @newsletter, notice: 'Newsletter was successfully updated.' }
        format.json { render :show, status: :ok, location: @newsletter }
      else
        format.html { render :edit }
        format.json { render json: @newsletter.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /newsletters/1
  # DELETE /newsletters/1.json
  def destroy
    @newsletter.destroy
    respond_to do |format|
      format.html { redirect_to newsletters_url, notice: 'Newsletter was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  # GET /newsletters/1/send
  def send_newsletter
    @newsletter = Newsletter.find(params[:newsletter_id])
    @produtos = Product.joins(
        "LEFT JOIN newsletters_products ON newsletters_products.newsletter_id = #{params[:newsletter_id]}
         LEFT JOIN contatos_products ON contatos_products.product_id = products.id
         LEFt JOIN contatos ON contatos_products.contato_id = contatos.id"
    )
    @contatos = @produtos[0].contatos
  end

  # POST /newsletters/1/send
  def send_mail
    @newsletter = Newsletter.find(params[:newsletter_id])
    @email = Email.find(params[:id])
    ContatoMailer.hello_email(email.contato, @newsletter).deliver_later

    render plain: @email.contato.to_json
=begin
    @newsletter = Newsletter.find(params[:newsletter_id])
    @emails = Email.find(params[:mass][:id])
    @emails.each do |email|
      #ContatoMailer.hello_email(email.contato, @newsletter).deliver_later
    end
    respond_to do |format|
      format.html { redirect_to @newsletter, notice: 'Enviado com sucesso.' }
      format.json { render :show, status: :ok, location: @newsletter }
    end
=end
  end

  # GET /newsletters/1/send
  def send_newsletterbkp
    @newsletter = Newsletter.find(params[:newsletter_id])
    @newsletter.products.each do |product|
      product.contatos.each do |contato|
        ContatoMailer.hello_email(contato, @newsletter).deliver_later
      end
    end
    respond_to do |format|
      format.html { redirect_to @newsletter, notice: 'Emviado com sucesso.' }
      format.json { render :show, status: :ok, location: @newsletter }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_newsletter
      @newsletter = Newsletter.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def newsletter_params
      params.require(:newsletter).permit(:subject, :html_message, :text_message, :status, product_ids:[])
    end
end

app/helpers/newsletters_helper.rb
module NewslettersHelper
end

app/views/newsletters/_form.html.erb
<%= form_for(@newsletter) do |f| %>
  <% if @newsletter.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@newsletter.errors.count, "error") %> prohibited this newsletter from being saved:</h2>

      <ul>
      <% @newsletter.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
  <div class="form-group">
    <%= f.label :subject, class: "label-control" %><br>
    <%= f.text_field :subject, class: 'form-control'  %>
  </div>
  <div class="form-group">
    <%= f.label :status, t('.status'), class:'label-control' %><br>
    <%= f.select :status, [[t('newsletters.model.status.1'), 1], [I18n.t('newsletters.model.status.0'), 0]], {}, {class:'form-control'} %>
  </div>
  <div class="form-group">
    <%= f.label :html_message, class: 'label-control' %><br>
    <%= f.text_area :html_message, class: 'form-control tinymce', :rows => 20, :cols => 120  %>
    <%= tinymce %>
  </div>
  <div class="form-group">
    <%= f.label :text_message, class: 'label-control' %><br>
    <%= f.text_area :text_message, class: 'form-control ', :rows => 20, :cols => 120  %>
  </div>
  <h3>Produtos de Interesse</h3>
  <div class="checkbox">
    <%= f.collection_check_boxes(:product_ids, Product.all, :id, :nome,  class: 'form-control', :item_wrapper_class => 'checkbox_container') do |product| %>
        <%= product.label  { product.check_box + product.text} %>
    <% end %>
  </div>
  <div class="actions">
    <%= f.submit class: 'btn btn-primary'%>
  </div>
<% end %>

app/views/newsletters/edit.html.erb
<h1><%= t('.title') %></h1>

<%= render 'form' %>

<%= link_to t('.show'), @newsletter %> |
<%= link_to t('.back'), newsletters_path %>

app/views/newsletters/index.html.erb
<p id="notice"><%= notice %></p>

<h1><%= t('.title') %></h1>

<table class="table table-striped">
  <thead>
    <tr>
      <th><%= t('.subject') %></th>
      <th><%= t('.html message') %></th>
      <th><%= t('.text message') %></th>
      <th><%= t('.status') %></th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @newsletters.each do |newsletter| %>
      <tr>
        <td><%= newsletter.subject %></td>
        <td><%= newsletter.html_message.html_safe %></td>
        <td><%= newsletter.text_message %></td>
        <td><%= newsletter.status %></td>
        <td><%= link_to t('.show'), newsletter %></td>
        <td><%= link_to t('.edit'), edit_newsletter_path(newsletter) %></td>
        <td><%= link_to t('.destroy'), newsletter, method: :delete, data: { confirm: t('.confirm') } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to t('.new newsletter'), new_newsletter_path %>

app/views/newsletters/new.html.erb
<h1><%= t('.title') %></h1>

<%= render 'form' %>

<%= link_to t('.back'), newsletters_path %>

app/views/newsletters/send_newsletter.html.erb
<p id="notice"><%= notice %></p>

<h1><%= t('.title') %></h1>
<%= form_tag  url: newsletter_send_mail_path, method: :post do  %>
    <%= submit_tag 'Send', {class: 'btn btn-primary', id:'sendMails'} %>
  <table class="table table-striped">
    <thead>
    <tr>
      <th><input type="checkbox" id="sendAll" name="mailler[mass][]" /></th>
      <th><%= t('.name') %></th>
      <th><%= t('.emails') %></th>
      <th>Status</th>
    </tr>
    </thead>

    <tbody>
      <% @contatos.each do |contato| %>
          <% contato.emails.each do |email| %>
            <tr>
              <td><input type="checkbox" class="mailerMass" id="mailler[mass][<%= email.id %>]" name="mass[id][]" value="<%= email.id %>" /></td>
              <td><%= contato.full_name %></td>
              <td><%= email.email %></td>
              <td class="status">-</td>
            </tr>
          <% end %>
      <% end %>
    </tbody>
  </table>

<% end %>
<%= link_to t('.back'), @newsletter %>

app/views/newsletters/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong><%= t('.status') %></strong>
</p>
<p>
  <%= @newsletter.status_text%>
</p>

<p>
  <strong><%= t('.subject') %>:</strong>
</p>
<p>
  <%= @newsletter.subject %>
</p>



<strong><%= t('.html message') %></strong>
<div class="bs-body">
  <p><%= @newsletter.html_message.html_safe  %></p>
</div>



<strong><%= t('.text message') %></strong>
<div class="bs-body">
  <p><%= @newsletter.text_message %></p>
</div>



<h3>Produtos</h3>
<ul>
  <% @newsletter.products.each do |product| %>
    <li>
      <h4><%= product.nome %></h4>
      <b>Clientes</b>
      <ul>
        <% product.contatos.each do |contato| %>
           <li>-<%= contato.full_name %></li>
        <% end %>
      </ul>
    </li>
  <% end %>
</ul>

<%= link_to t('.edit'), edit_newsletter_path(@newsletter) %> |
<%= link_to t('.back'), newsletters_path %> |
<%= link_to t('.send'), newsletter_send_newsletter_path(@newsletter) %>