config/routes.rb
Rails.application.routes.draw do

  root 'static_pages#home'
  get 'about', controller:  :static_pages
  get 'vcard/upload'

  resources :newsletters do
    get 'send_newsletter'
    post 'send_mail'
  end
  devise_for :users, controllers: {sessions: "usuario/sessions"}

  resources :contatos do
    get 'migrate'
    collection do
      post :mass_action
    end
    resources :notes, :only => [:edit, :create, :update, :index, :destroy]
  end
  resources :ajaxcontatos

  namespace :usuario do
    resources :generals
    resources :messages
    resources :roles
  end

  namespace :credit do
    resources :documents
    namespace :bank do
      resources :generals
    end
    namespace :client do
      resources :generals do
        get 'find_expired'
      end
      namespace :partner do
        resources :document_lists
      end
      namespace :warranty do
        resources :document_lists
      end
    end
  end

  namespace :business do
    resources :notes
    resources :histories
    resources :generals
    resources :internationals
    resources :nationals
    resources :sites
  end

  namespace :internationals do
    resources :generals
  end

  namespace :juridico do
    resources :andamentos
    resources :processos
  end

  namespace :product do
    resources :documents
    resources :generals
    resources :internationals
    resources :nationals
    namespace :thirdparty do
      resources :bases
    end
  end

end

app/models/business/general.rb
class Business::General < ActiveRecord::Base
  delegate :international, :national, :site, to: :product_general

  has_and_belongs_to_many :contatos, class_name:'Contato', foreign_key: "business_generals_id", association_foreign_key: "contato_id",  join_table: "business_generals_contacts"
  accepts_nested_attributes_for :contatos
  belongs_to :product_general,  class_name:'Product::General'

  #One-to-Many
  #One Contato has many emails
  has_many :histories, foreign_key: "business_general_id"
  accepts_nested_attributes_for :histories, reject_if: proc { |attributes| attributes['note'].blank? or attributes['date_entry'].blank? }, :allow_destroy => true

  has_many :notes, foreign_key: "business_general_id"
  accepts_nested_attributes_for :notes, reject_if: proc { |attributes| attributes['note'].blank? }, :allow_destroy => true

  has_many :intermediary_contatos, class_name: '::Contato', foreign_key: 'business_general_id', through: :intermediaries, :source => 'contato'
  accepts_nested_attributes_for :intermediary_contatos, :allow_destroy => true, :reject_if => :all_blank

  has_many :intermediaries, class_name: 'Business::Intermediary',  inverse_of: :business_general, foreign_key: 'business_general_id', dependent: :destroy
  accepts_nested_attributes_for :intermediaries, :allow_destroy => true, :reject_if => :all_blank

  def getType
    case self.type
      when 'Business::International'
        return 'Operação Internacional'
      when 'Business::National'
        return 'Negocios'
      when 'Business::Site'
        return 'Consulta Site'
    end
  end

end

app/models/business/history.rb
class Business::History < ApplicationRecord
  belongs_to :general
end

app/models/business/intermediary.rb
class Business::Intermediary < ApplicationRecord
  belongs_to :business_general
  belongs_to :contato, foreign_key: 'contato_id', class_name: "::Contato"
  accepts_nested_attributes_for :contato, :allow_destroy => true, :reject_if => :all_blank
end

app/controllers/business/generals_controller.rb
class Business::GeneralsController < ApplicationController
  before_action :set_business_general, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!

  # GET /business/generals
  # GET /business/generals.json
  def index
    @business_generals = Business::General.all
  end

  # GET /business/generals/1
  # GET /business/generals/1.json
  def show
  end

  # GET /business/generals/new
  def new

    @business_general = Business::General.new
    #@business_general.histories.build
    #@business_general.histories.build
    @business_general.notes.build
    @business_general.intermediaries.build
    @business_general.contatos.build
  end

  # GET /business/generals/1/edit
  def edit
    @business_general.histories.build
    @business_general.notes.build
    @business_general.contatos.build
    @business_general.intermediaries.build
  end

  # POST /business/generals
  # POST /business/generals.json
  def create
    @business_general = Business::General.new(business_general_params)

    respond_to do |format|
      if @business_general.save
        format.html { redirect_to @business_general, notice: 'General was successfully created.' }
        format.json { render :show, status: :created, location: @business_general }
      else
        format.html { render :new }
        format.json { render json: @business_general.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /business/generals/1
  # PATCH/PUT /business/generals/1.json
  def update
    respond_to do |format|
      if @business_general.update(business_general_params)
        format.html { redirect_to @business_general, notice: 'General was successfully updated.' }
        format.json { render :show, status: :ok, location: @business_general }
      else
        format.html { render :edit }
        format.json { render json: @business_general.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /business/generals/1
  # DELETE /business/generals/1.json
  def destroy
    @business_general.destroy
    respond_to do |format|
      format.html { redirect_to business_generals_url, notice: 'General was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_business_general
      @business_general = Business::General.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def business_general_params
      params.require(:business_general).permit(:id, :name, :date_entry, :subject,  :product_general_id, :conditions, :type,
                                               {intermediary_contato_ids:[]},
                                               {contato_ids:[]},
                                               {histories_attributes: [:id, :date_entry, :note]},
                                               {notes_attributes: [:id, :note]},
                                               {intermediary_attributes: [:id, :note, :contato_id]}
      )

    end
end

app/controllers/business/histories_controller.rb
class Business::HistoriesController < ApplicationController
  before_action :set_business_history, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!

  # GET /business/histories
  # GET /business/histories.json
  def index
    @business_histories = Business::History.all
  end

  # GET /business/histories/1
  # GET /business/histories/1.json
  def show
  end

  # GET /business/histories/new
  def new
    @business_history = Business::History.new
  end

  # GET /business/histories/1/edit
  def edit
  end

  # POST /business/histories
  # POST /business/histories.json
  def create
    @business_history = Business::History.new(business_history_params)

    respond_to do |format|
      if @business_history.save
        format.html { redirect_to @business_history, notice: 'History was successfully created.' }
        format.json { render :show, status: :created, location: @business_history }
      else
        format.html { render :new }
        format.json { render json: @business_history.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /business/histories/1
  # PATCH/PUT /business/histories/1.json
  def update
    respond_to do |format|
      if @business_history.update(business_history_params)
        format.html { redirect_to @business_history, notice: 'History was successfully updated.' }
        format.json { render :show, status: :ok, location: @business_history }
      else
        format.html { render :edit }
        format.json { render json: @business_history.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /business/histories/1
  # DELETE /business/histories/1.json
  def destroy
    @business_history.destroy
    respond_to do |format|
      format.html { redirect_to business_histories_url, notice: 'History was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_business_history
      @business_history = Business::History.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def business_history_params
      params.require(:business_history).permit(:data_entry, :note, :business_general_id)
    end
end

app/controllers/business/internationals_controller.rb
class Business::InternationalsController < ApplicationController
  before_action :set_business_international, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!

  # GET /business/internationals
  # GET /business/internationals.json
  def index
    @business_generals = Business::International.all
  end

  # GET /business/internationals/1
  # GET /business/internationals/1.json
  def show
  end

  # GET /business/internationals/new
  def new

    @business_general = Business::International.new
    #@business_general.histories.build
    #@business_general.histories.build
    @business_general.notes.build
    @business_general.intermediaries.build
    @business_general.contatos.build
  end

  # GET /business/internationals/1/edit
  def edit
    @business_general.histories.build
    @business_general.notes.build
    @business_general.contatos.build
    @business_general.intermediaries.build
  end

  # POST /business/internationals
  # POST /business/internationals.json
  def create
    @business_general = Business::International.new(business_international_params)

    respond_to do |format|
      if @business_general.save
        format.html { redirect_to @business_general, notice: 'International was successfully created.' }
        format.json { render :show, status: :created, location: @business_general }
      else
        format.html { render :new }
        format.json { render json: @business_general.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /business/internationals/1
  # PATCH/PUT /business/internationals/1.json
  def update
    respond_to do |format|
      if @business_general.update(business_international_params)
        format.html { redirect_to @business_general, notice: 'International was successfully updated.' }
        format.json { render :show, status: :ok, location: @business_general }
      else
        format.html { render :edit }
        format.json { render json: @business_general.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /business/internationals/1
  # DELETE /business/internationals/1.json
  def destroy
    @business_general.destroy
    respond_to do |format|
      format.html { redirect_to business_internationals_url, notice: 'International was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_business_international
      begin
        @business_general = Business::International.find(params[:id])
      rescue
        @business_general = Business::General.find(params[:id])
        refirect_to @business_general
      end
    end


    # Never trust parameters from the scary internet, only allow the white list through.
    def business_international_params
      params.require(:business_international).permit(:id, :name, :date_entry, :subject,  :product_general_id, :conditions, :type,
                                                     {intermediary_contato_ids:[]},
                                                     {contato_ids:[]},
                                                     {histories_attributes: [:id, :date_entry, :note]},
                                                     {notes_attributes: [:id, :note]},
                                                     {intermediary_attributes: [:id, :note, :contato_id]}
      )

    end
end

app/controllers/business/nationals_controller.rb
class Business::NationalsController < Business::GeneralsController
  before_action :set_business_national, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!

  # GET /business/nationals
  # GET /business/nationals.json
  def index
    @business_generals = Business::National.all
  end


  # GET /business/nationals/new
  def new

    @business_general = Business::National.new
    #@business_general.histories.build
    #@business_general.histories.build
    @business_general.notes.build
    @business_general.intermediaries.build
    @business_general.contatos.build
  end


  # POST /business/nationals
  # POST /business/nationals.json
  def create
    @business_general = Business::National.new(business_national_params)

    respond_to do |format|
      if @business_general.save
        format.html { redirect_to @business_general, notice: 'National was successfully created.' }
        format.json { render :show, status: :created, location: @business_general }
      else
        format.html { render :new }
        format.json { render json: @business_general.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /business/nationals/1
  # PATCH/PUT /business/nationals/1.json
  def update
    respond_to do |format|
      if @business_general.update(business_national_params)
        format.html { redirect_to @business_general, notice: 'National was successfully updated.' }
        format.json { render :show, status: :ok, location: @business_general }
      else
        format.html { render :edit }
        format.json { render json: @business_general.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /business/nationals/1
  # DELETE /business/nationals/1.json
  def destroy
    @business_general.destroy
    respond_to do |format|
      format.html { redirect_to business_nationals_url, notice: 'National was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
  # Use callbacks to share common setup or constraints between actions.
  def set_business_national
    begin
      @business_general = Business::National.find(params[:id])
    rescue
      @business_general = Business::General.find(params[:id])
    end
  end

  # Never trust parameters from the scary internet, only allow the white list through.
  def business_national_params
    params.require(:business_national).permit(:id, :name, :date_entry, :subject,  :product_general_id, :conditions, :type,
                                              {intermediary_contato_ids:[]},
                                              {contato_ids:[]},
                                              {histories_attributes: [:id, :date_entry, :note]},
                                              {notes_attributes: [:id, :note]},
                                              {intermediary_attributes: [:id, :note, :contato_id]}
    )
  end
end

app/controllers/business/notes_controller.rb
class Business::NotesController < ApplicationController
  before_action :set_business_note, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!

  # GET /business/notes
  # GET /business/notes.json
  def index
    @business_notes = Business::Note.all
  end

  # GET /business/notes/1
  # GET /business/notes/1.json
  def show
  end

  # GET /business/notes/new
  def new
    @business_note = Business::Note.new
  end

  # GET /business/notes/1/edit
  def edit
  end

  # POST /business/notes
  # POST /business/notes.json
  def create
    @business_note = Business::Note.new(business_note_params)

    respond_to do |format|
      if @business_note.save
        format.html { redirect_to @business_note, notice: 'Note was successfully created.' }
        format.json { render :show, status: :created, location: @business_note }
      else
        format.html { render :new }
        format.json { render json: @business_note.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /business/notes/1
  # PATCH/PUT /business/notes/1.json
  def update
    respond_to do |format|
      if @business_note.update(business_note_params)
        format.html { redirect_to @business_note, notice: 'Note was successfully updated.' }
        format.json { render :show, status: :ok, location: @business_note }
      else
        format.html { render :edit }
        format.json { render json: @business_note.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /business/notes/1
  # DELETE /business/notes/1.json
  def destroy
    @business_note.destroy
    respond_to do |format|
      format.html { redirect_to business_notes_url, notice: 'Note was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_business_note
      @business_note = Business::Note.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def business_note_params
      params.require(:business_note).permit(:note, :business_general_id)
    end
end

app/helpers/business/generals_helper.rb
module Business::GeneralsHelper
end

app/helpers/business/histories_helper.rb
module Business::HistoriesHelper
end

app/helpers/business/notes_helper.rb
module Business::NotesHelper
end

app/views/business/internationals/_contato_fields.html.erb
<div class="form-item">
  <div class="row">
    <div class="col-md-12">
      <h4><%= I18n.t('Contact.view.Contact_Information') %></h4>
      <hr>
    </div>
  </div>
  <div class="row">
    <div class="col-md-6">
      <%= f.input :id, label:'Contato', as: :select, collection: Contato.all, :label_method => :full_name,  input_html: {class: 'chosen-select credit_client_international_contato_id'} %>
    </div>
  </div>
  <div class="row">
    <div class="col-md-6">
      <%= f.input :first_name%>
    </div>
    <div class="col-md-6">
      <%= f.input :last_name%>
    </div>
    <div class="col-md-6">
      <%= f.input :web_page%>
    </div>
  </div>

  <fieldset id="emails">
    <div class="col-md-12">
      <h4>
        <button class="btn" id="btn_emails">
          <%= link_to_add_association '+', f, :emails, partial: 'credit/client/internationals/contatos/email_fields' %>
        </button>
        <%= I18n.t('Contact.model.Emails') %>
      </h4>
      <hr>
    </div><br>
    <div class="fields">
      <%= f.simple_fields_for :emails do |email| %>
          <%= render 'contatos/email_fields', :f => email %>
      <% end %>
    </div>
  </fieldset>

  <fieldset id="telefones">
    <div class="col-md-12">
      <h4>
        <button class="btn" id="btn_telefones">
          <%= link_to_add_association '+', f, :telefones, partial: 'credit/client/internationals/contatos/phone_fields' %>
        </button>
        <%= I18n.t('Contact.model.Phones') %>
      </h4>
      <hr>
    </div><br>
    <div class="fields">
      <%= f.simple_fields_for :telefones do |telefone| %>
          <%= render 'contatos/phone_fields', :f => telefone %>
      <% end %>
    </div>
  </fieldset>

</div>

app/views/business/internationals/_form.html.erb
<script>
    $( document ).ready(function() {
        $('#myTabs a').click(function (e) {
            e.preventDefault()
            $(this).tab('show')
        })
        $('#myTabs2 a').click(function (e) {
            e.preventDefault()
            $(this).tab('show')
        })
    });
</script>
<%= simple_form_for(@business_general) do |f| %>
  <% if business_international.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(business_international.errors.count, "error") %> prohibited this business_international from being saved:</h2>

      <ul>
      <% business_international.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
  <ul class="nav nav-tabs" id="myTabs">
    <li class="active"><a class="tablink " href="#data" data-turbolinks="false">Dados Cadastrais</a></li>
    <li><a class="tablink" href="#intermediary" data-turbolinks="false"><%= t('.intermediary') %></a></li>
  </ul>
  <div class="tab-content clearfix" style="color: #555555;
      background-color: #fff;
      padding: 20px;
      border: 1px solid #ddd;
      margin-bottom: 40px;
      border-top-color: transparent;">
    <div class="tab-pane active" id="data">
      <div class="form-group row">
        <div class="col-md-12">
          <%= f.input :name %>
        </div>
        <div class="col-md-12">
          <%= f.input :subject %>
        </div>
      </div>
      <div class="form-group row">
        <div class="form-inline col-md-3">
          <%= f.label :date_entry, class: "form-label" %>
          <%= f.date_field :date_entry, class: 'form-control'  %>
        </div>
        <div class="col-md-4">
          <%= f.association :product_general, label_method: :nome %>
        </div>
        <div class="col-md-12">
          <%= f.input :conditions %>
        </div>
      </div>
      <div id="contato">
        <fieldset id="contatos">
          <div class="col-md-12">
            <h4>
              <%= t('.contacts') %>
            </h4>
            <hr>
          </div><br>
          <div class="contato_menu" id="alfa">
            <%= link_to '+Novo Contato', new_ajaxcontato_path,
                        :remote => true, data: { modal: true } %>
            <%= f.association :contatos, label_method: :full_name, input_html: {class: 'contato'}  %>
          </div>

          <table class="table table-stripped fields"></table>

        </fieldset>
      </div>

      <hr>
      <fieldset id="notes">
        <div class="col-md-12">
          <h4><%= t('.add_note') %></h4>

        </div><br>
        <div class="fields">
          <%= f.fields_for :notes do |note| %>
              <%= render 'note_fields', :f => note %>
          <% end %>
        </div>
        <div class='links'>
          <button class="btn" id="btn_notes"><%= link_to_add_association t('.add_note'), f, :notes %></button>
        </div>
        <hr>
      </fieldset>
      <hr>
      <fieldset id="histories">
        <div class="col-md-12">
          <h4><%= t('.add_history') %></h4>
        </div><br>
        <div class="fields">
          <%= f.fields_for :histories do |history| %>
              <%= render 'history_fields', :f => history %>
          <% end %>
        </div>
        <div class='links'>
          <button class="btn" id="btn_histories"><%= link_to_add_association t('.add_history'), f, :histories %></button>
        </div>
        <hr>
      </fieldset>


    </div>
    <div class="tab-pane" id="intermediary">
      <% #@TODO Colocar telefone como campo único%>
      <fieldset id="intermediarys" class="col-md-12">
        <div class="fields row">
          <fieldset id="contatos">
            <div class="col-md-12">
              <h4>
                <%= t('.contacts') %>
              </h4>
              <hr>
            </div><br>
            <div class="contato_menu" id="alfa">
              <%= link_to '+Novo Contato', new_ajaxcontato_path,
                          :remote => true, data: { modal: true } %>
              <%= f.association :intermediary_contatos, label_method: :full_name %>
            </div>
            <table class="table table-stripped fields"></table>
          </fieldset>

        </div>
      </fieldset>
    </div>
  </div>
    <div class="actions">
      <%= f.submit %>
    </div>
<% end %>

app/views/business/internationals/_history_fields.html.erb
<div class="form-group form-item row">
  <%= f.hidden_field :id %>
  <div class="col-md-3 form-inline">
    <%= f.date_field :date_entry,  class: 'form-control' %>
  </div>
  <div class="col-md-7"><%= f.text_area :note, rows: "5", class: 'form-control' %></div>

  <div class="checkbox col-md-2">
    <label>
      <%= f.check_box :_destroy %>
      <%= f.label :_destroy, I18n.t('remove') %>
    </label>
  </div>
  <hr>
</div>

app/views/business/internationals/_note_fields.html.erb
<div class="form-group form-item row">
  <%= f.hidden_field :id %>
  <div class="col-md-10"><%= f.text_area :note, rows: "5", class: 'form-control' %></div>

  <div class="checkbox col-md-2">
    <label>
      <%= f.check_box :_destroy %>
      <%= f.label :_destroy, I18n.t('remove') %>
    </label>
  </div>
  <hr>
</div>

app/views/business/internationals/edit.html.erb
<h1><%= t('.title') %></h1>

<%= render 'form', business_international: @business_general %>

<%= link_to t('.show'), @business_general %> |
<%= link_to t('.back'), business_internationals_path %>

app/views/business/internationals/index.html.erb
<p id="notice"><%= notice %></p>

<h1><%= t('.title') %></h1>

<table class="table">
  <thead class="header-table">
    <tr>
      <th><%= t('.date_entry') %></th>
      <th><%= t('.subject') %></th>
      <th>Contato</th>
      <th><%= t('.product') %></th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @business_generals.each do |business_international| %>
      <tr>
        <td><%= business_international.date_entry %></td>
        <td><%= business_international.subject %></td>
        <td><% business_international.contatos.each do |contato| %>
          <%= contato.full_name %>,
          <% end %></td>
        <td><%= !business_international.product_general.nil? ? business_international.product_general.nome :  '--'  %></td>
        <td><%= link_to t('.show'), business_international %></td>
        <td><%= link_to t('.edit'), edit_business_international_path(business_international) %></td>
        <td><%= link_to t('.destroy'), business_international, method: :delete, data: { confirm: t('.destroy_msg') } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to t('.new'), new_business_international_path %>

app/views/business/internationals/new.html.erb
<h1><%= t('.title') %></h1>

<%= render 'form', business_international: @business_general %>

<%= link_to t('.back'), business_internationals_path %>

app/views/business/internationals/show.html.erb
<style>
  .square{
    color: #555555;
    background-color: #fff;
    padding: 20px;
    border: 1px solid #ddd;
    border-top-color: transparent;
  }
  .top_square{
    color: #555555;
    background-color: #fff;
    padding: 20px;
    border: 1px solid #ddd;
  }
  .title_square{
    color: #555555;
    background-color: #fff;
    padding: 10px;
    border: 1px solid #ddd;
    border-top-color: transparent;
  }
</style>
<div class="row" style="margin: 40px 0;">
  <div class="col-xs-12">
    <img src="<%= request.base_url %>/img/logo.png">
  </div>
</div>
<div class="row top_square">
  <div class="col-xs-8">
    <strong>Nome:</strong>
    <%= @business_general.name %>
  </div>
  <div class="col-xs-4">
    <strong>Assunto:</strong>
    <%= @business_general.subject %>
  </div>
  <div class="col-xs-8">
    <strong>Data de Entrada: </strong>
    <%= @business_general.date_entry %>
  </div>
  <div class="col-xs-4">
    <strong>Produto:</strong>
    <%= !@business_general.product_general.nil? ? @business_general.product_general.nome :  '--'  %>
  </div>
  <div class="col-xs-12">
    <strong>Condições</strong>
    <%= @business_general.conditions %>
  </div>
</div>

<% if !@business_general.contatos.nil? %>
    <div class="row  title_square">
      <div class="col-xs-12">
        <h4><strong><%= t('.contato') %></strong></h4>
      </div>
    </div>
    <div class="row square">
      <% @business_general.contatos.each do |contato| %>
          <div class="col-xs-12">Nome: <%= contato.full_name %></div>
          <div class="col-xs-6">
            <h5><strong>Telefones</strong></h5>
            <ul>
              <% contato.telefones.each do |phone| %>
                  <li><%= "(#{phone.ddd}) #{phone.telefone} - #{phone.tipo}" %></li>
              <% end %>
            </ul>
          </div>
          <div class="col-xs-6">
            <h5><strong>Emails</strong></h5>
            <ul>
              <% contato.emails.each do |email| %>
                  <li><%= email.email %></li>
              <% end %>
            </ul>
          </div>
      <% end %>
    </div>
<% end %>

<% if (!@business_general.intermediaries.nil?) %>
  <div class="row  title_square">
    <div class="col-xs-12">
      <h4><strong>Intermediário</strong></h4>
    </div>
  </div>
  <% @business_general.intermediaries.each do  |intermediary| %>
    <div class="row square">
      <% if !intermediary.contato.nil? %>
          <div class="col-xs-12">Nome: <%= intermediary.contato.full_name %></div>
          <div class="col-xs-6">
            <h5><strong>Telefones</strong></h5>
            <ul>
              <% intermediary.contato.telefones.each do |phone| %>
                  <li><%= "(#{phone.ddd}) #{phone.telefone} - #{phone.tipo}" %></li>
              <% end %>
            </ul>
          </div>
          <div class="col-xs-6">
            <h5><strong>Emails</strong></h5>
            <ul>
              <% intermediary.contato.emails.each do |email| %>
                  <li><%= email.email %></li>
              <% end %>
            </ul>
          </div>
          <div class="col-xs-12">
            <h5><strong>Observações</strong></h5>
            <%= intermediary.note %>
          </div>
      <% end %>
    </div>
  <% end %>
<% end %>

<% if (!@business_general.notes.nil?) %>
  <div class="row title_square">
    <div class="col-xs-12">
      <h4><strong>Anotacões</strong></h4>
    </div>
  </div>
  <div class="row square">
    <% @business_general.notes.each do |note| %>
        <div class="col-xs-12"><%= note.note %></div>
    <% end %>
  </div>
<% end %>

<% if (!@business_general.histories.nil?) %>
<div class="row title_square">
  <div class="col-xs-12">
    <h4><strong>Histórico</strong></h4>
  </div>
</div>
<div class="row square">
  <% @business_general.histories.each do |history| %>
      <div class="col-xs-3">Data: <%= history.date_entry.strftime("%d/%m/%Y") %></div>
      <div class="col-xs-9"><%= history.note %></div>
  <% end %>
</div>
<% end %>



<div class="hidden-print">
  <%= link_to t('.edit'), edit_business_international_path(@business_general) %> |
  <%= link_to t('.back'), business_internationals_path %>
</div>