config/routes.rb
Rails.application.routes.draw do

  root 'static_pages#home'
  get 'about', controller:  :static_pages
  get 'vcard/upload'

  resources :newsletters do
    get 'send_newsletter'
    post 'send_mail'
  end
  devise_for :users, controllers: {sessions: "usuario/sessions"}

  resources :contatos do
    get 'migrate'
    collection do
      post :mass_action
    end
    resources :notes, :only => [:edit, :create, :update, :index, :destroy]
  end
  resources :ajaxcontatos

  namespace :usuario do
    resources :generals
    resources :messages
    resources :roles
  end

  namespace :credit do
    resources :documents
    namespace :bank do
      resources :generals
    end
    namespace :client do
      resources :generals do
        get 'find_expired'
      end
      namespace :partner do
        resources :document_lists
      end
      namespace :warranty do
        resources :document_lists
      end
    end
  end

  namespace :business do
    resources :notes
    resources :histories
    resources :generals
    resources :internationals
    resources :nationals
    resources :sites
  end

  namespace :internationals do
    resources :generals
  end

  namespace :juridico do
    resources :andamentos
    resources :processos
  end

  namespace :product do
    resources :documents
    resources :generals
    resources :internationals
    resources :nationals
    namespace :thirdparty do
      resources :bases
    end
  end

end

app/models/juridico.rb
module Juridico
  def self.table_name_prefix
    'juridico_'
  end
end

app/models/juridico/andamento.rb
class Juridico::Andamento < ActiveRecord::Base
  belongs_to :processo
end

app/models/juridico/processo.rb
class Juridico::Processo < ActiveRecord::Base
  has_many :andamentos
  accepts_nested_attributes_for :andamentos,
                                reject_if: proc { |attributes| attributes['nota'].blank? },
                                :allow_destroy => true
  def category_text
    if self.category == 1
      return 'Civil'
    elsif self.category == 2
      return 'Trabalhista'
    end
  end

  def free_text
    if self.free == 1
      'Sim'
    else
      'Não'
    end
  end
end

app/controllers/juridico/andamentos_controller.rb
class Juridico::AndamentosController < ApplicationController
  before_action :set_juridico_andamento, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!

  # GET /juridico/andamentos
  # GET /juridico/andamentos.json
  def index
    @juridico_andamentos = Juridico::Andamento.all
  end

  # GET /juridico/andamentos/1
  # GET /juridico/andamentos/1.json
  def show
  end

  # GET /juridico/andamentos/new
  def new
    @juridico_andamento = Juridico::Andamento.new
  end

  # GET /juridico/andamentos/1/edit
  def edit
  end

  # POST /juridico/andamentos
  # POST /juridico/andamentos.json
  def create
    @juridico_andamento = Juridico::Andamento.new(juridico_andamento_params)

    respond_to do |format|
      if @juridico_andamento.save
        format.html { redirect_to @juridico_andamento, notice: 'Andamento was successfully created.' }
        format.json { render :show, status: :created, location: @juridico_andamento }
      else
        format.html { render :new }
        format.json { render json: @juridico_andamento.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /juridico/andamentos/1
  # PATCH/PUT /juridico/andamentos/1.json
  def update
    respond_to do |format|
      if @juridico_andamento.update(juridico_andamento_params)
        format.html { redirect_to @juridico_andamento, notice: 'Andamento was successfully updated.' }
        format.json { render :show, status: :ok, location: @juridico_andamento }
      else
        format.html { render :edit }
        format.json { render json: @juridico_andamento.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /juridico/andamentos/1
  # DELETE /juridico/andamentos/1.json
  def destroy
    @juridico_andamento.destroy
    respond_to do |format|
      format.html { redirect_to juridico_andamentos_url, notice: 'Andamento was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_juridico_andamento
      @juridico_andamento = Juridico::Andamento.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def juridico_andamento_params
      params.require(:juridico_andamento).permit(:nota, :data, :processo_id)
    end
end

app/controllers/juridico/processos_controller.rb
class Juridico::ProcessosController < ApplicationController
  before_action :set_juridico_processo, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!


  # GET /juridico/processos
  # GET /juridico/processos.json
  def index
    @juridico_processos = Juridico::Processo.all
  end

  # GET /juridico/processos/1
  # GET /juridico/processos/1.json
  def show
  end

  # GET /juridico/processos/new
  def new
    @juridico_processo = Juridico::Processo.new

  end

  # GET /juridico/processos/1/edit
  def edit
    build_processo
  end

  # POST /juridico/processos
  # POST /juridico/processos.json
  def create
    @juridico_processo = Juridico::Processo.new(juridico_processo_params)

    respond_to do |format|
      if @juridico_processo.save
        format.html { redirect_to @juridico_processo, notice: 'Processo was successfully created.' }
        format.json { render :show, status: :created, location: @juridico_processo }
      else
        format.html { render :new }
        format.json { render json: @juridico_processo.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /juridico/processos/1
  # PATCH/PUT /juridico/processos/1.json
  def update

    respond_to do |format|
      if @juridico_processo.update(juridico_processo_params)
        format.html { redirect_to @juridico_processo, notice: 'Processo was successfully updated.' }
        format.json { render :show, status: :ok, location: @juridico_processo }
      else
        format.html { render :edit }
        format.json { render json: @juridico_processo.errors, status: :unprocessable_entity }
      end
    end

  end

  # DELETE /juridico/processos/1
  # DELETE /juridico/processos/1.json
  def destroy
    @juridico_processo.destroy
    respond_to do |format|
      format.html { redirect_to juridico_processos_url, notice: 'Processo was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_juridico_processo
      @juridico_processo = Juridico::Processo.find(params[:id])
    end

    #build contact relationships
    def build_processo
      @juridico_processo.andamentos.build
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def juridico_processo_params
      params.require(:juridico_processo).permit(:number, :category, :author, :defendant, :date, :shire, :circuit, :value, :free, :notes, andamentos_attributes:[:id, :data, :nota, :_destroy])
    end
end

app/helpers/juridico/andamentos_helper.rb
module Juridico::AndamentosHelper
end

app/helpers/juridico/processos_helper.rb
module Juridico::ProcessosHelper
end

app/views/juridico/processos/_andamento_fields.html.erb
<div class="form-group form-item row">
  <%= f.hidden_field :id %>
  <div class="col-md-4 form-inline">
    <%= f.date_select :data, {:order => [:day, :month, :year],
                              :use_month_numbers => true,
                              :start_year => 2000,
                              :end_year => Time.current.year},
                      {:class => 'form-control'} %>
  </div>
  <div class="col-md-6"><%= f.text_area :nota, rows: "5", class: 'form-control' %></div>

  <div class="checkbox col-md-2">
    <label>
      <%= f.check_box :_destroy %>
      <%= f.label :_destroy, I18n.t('remove') %>
    </label>
  </div>
  <hr>
</div>

app/views/juridico/processos/_form.html.erb
<%= form_for(@juridico_processo) do |f| %>
  <% if @juridico_processo.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@juridico_processo.errors.count, "error") %> prohibited this juridico_processo from being saved:</h2>

      <ul>
      <% @juridico_processo.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
  <div class="groupo">
    <div class="col-md-6 form-group">
      <%= f.label :number, class: 'control-label' %>
      <%= f.text_field :number, class: 'form-control' %>
    </div>
    <div class="col-md-6 form-group">
      <%= f.label :category, class: 'control-label' %>
      <%= f.select :category, [['Civil', 1], ['Trabalhista',2]], {}, {class:'form-control'} %>
    </div>
  </div>
    <div class="groupo">
      <div class="col-md-4 form-group">
        <%= f.label :judge, class: 'control-label' %>
        <%= f.text_field :judge, class: 'form-control' %>
      </div>
      <div class="col-md-4 form-group">
        <%= f.label :classe, class: 'control-label' %>
        <%= f.text_field :classe, class:'form-control' %>
      </div>
    </div>
  <div class="groupo">
    <div class="col-md-5 form-group">
    <%= f.label :author, class: 'control-label' %>
    <%= f.text_field :author, class: 'form-control' %>
    </div>
    <div class="col-md-5 form-group">
      <%= f.label :defendant, class: 'control-label' %>
      <%= f.text_field :defendant, class: 'form-control' %>
    </div>
    <div class="col-md-2 form-group">
      <%= f.label :free, class: 'control-label' %>
      <div>
      <%= label_tag :free, class: 'checkbox-inline' do %>
          <%= f.check_box :free, class: 'checkbox' %>
          <%= t('.free_justice') %>
      <% end %>
      </div>


    </div>
  </div>
  <div class="groupo">
    <div class="col-md-4 form-group form-inline">
      <%= f.label :date, class: 'control-label' %><br>
      <%= f.date_select :date,
                      {:order => [:day, :month, :year],
                      :start_year => 2000,
                      :end_year => Time.current.year},
                      {:class => 'form-control'}
      %>
    </div>
    <div class="col-md-3 form-group">
      <%= f.label :shire, class: 'control-label' %><br>
      <%= f.text_field :shire, class: 'form-control' %>
    </div>
    <div class="col-md-3 form-group">
      <%= f.label :circuit, class: 'control-label' %><br>
      <%= f.text_field :circuit, class: 'form-control' %>
    </div>
    <div class="col-md-2 form-group">
      <%= f.label :value, class: 'control-label' %><br>
      <%= f.text_field :value, class: 'form-control' %>
    </div>

  </div>

    <fieldset id="andamentos" class="col-md-12">

      <div class="col-md-12">
        <h4><%= t('.andamento') %></h4>
        <button class="btn" id="btn_andamentos"><%= link_to_add_association t('.add_andamento'), f, :andamentos %></button>
        <hr>
      </div><br>
      <div class="fields row">
        <%= f.fields_for :andamentos do |andamento| %>
            <%= render 'andamento_fields', :f => andamento %>
        <% end %>
      </div>

      <hr>
    </fieldset>
  <div class="col-md-12 form-group">
    <%= f.label :notes, class: 'control-label' %><br>
    <%= f.text_area :notes, class: 'form-control' %>
  </div>



  <div class="actions col-md-12 form-group">
    <%= f.submit class: 'btn btn-primary' %>
  </div>
<% end %>

app/views/juridico/processos/edit.html.erb
<h1><%= t('.title') %></h1>
<div class="row" style="padding:20px 0px;">
  <div class="col-md-2 col-md-offset-10">
    <%= link_to t('.show'), @juridico_processo %> |
    <%= link_to t('.back'), juridico_processos_path %>
  </div>
</div>
<div class="container">
  <%= render 'form' %>
</div>

app/views/juridico/processos/index.html.erb
<p id="notice"><%= notice %></p>

<h1><%= t('.title') %></h1>

<table class="table table-striped">
  <thead>
    <tr>
      <th><%= t('.category') %></th>
      <th><%= t('.author') %></th>
      <th><%= t('.defendant') %></th>
      <th><%= t('.free') %></th>
      <th><%= t('.shire') %></th>
      <th><%= t('.circuit') %></th>
      <th colspan="2"></th>
    </tr>
  </thead>

  <tbody>
    <% @juridico_processos.each do |juridico_processo| %>
      <tr>
        <td><%= juridico_processo.category_text %></td>
        <td><%= juridico_processo.author %></td>
        <td><%= juridico_processo.defendant %></td>
        <td><%= juridico_processo.free_text %></td>
        <td><%= juridico_processo.shire %></td>
        <td><%= juridico_processo.circuit %></td>
        <td colspan="2">
          <div class="dropdown">
            <button class="btn btn-default dropdown-toggle" type="button" id="dropdownMenu1" data-toggle="dropdown" aria-haspopup="true" aria-expanded="true">
              <%= I18n.t('Actions') %>
              <span class="caret"></span>
            </button>
            <ul class="dropdown-menu" aria-labelledby="dropdownMenu1">
              <li><%= link_to I18n.t('Show'), juridico_processo %></li>
              <li><%= link_to I18n.t('Edit'),  edit_juridico_processo_path(juridico_processo) %></li>
              <li role="separator" class="divider"></li>
              <li><%= link_to I18n.t('Destroy'), juridico_processo, method: :delete, data: { confirm: I18n.t('Are_you_sure?') } %></li>
            </ul>
          </div>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to t('.add'), new_juridico_processo_path %>

app/views/juridico/processos/new.html.erb
<h1><%= t('.title') %></h1>
<div class="row" style="padding:20px 0px;">
  <div class="col-md-1 col-md-offset-11">
    <%= link_to t('.back'), contatos_path %>
  </div>
</div>
<div class="container">
  <%= render 'form' %>
</div>

app/views/juridico/processos/show.html.erb
<section id="dados">
  <div class="row">
    <div class="col-md-12">
      <p><strong><%= t('.number') %></strong> <%= @juridico_processo.number %></p>
    </div>
  </div>
  <div class="row">
    <div class="col-md-12">
      <p><strong><%= t('.classe') %></strong> <%= @juridico_processo.classe %></p>
    </div>
  </div>
  <div class="row">
    <div class="col-md-12">
      <p><strong><%= t('.category') %></strong>
      <%= @juridico_processo.category_text %></p>
    </div>
  </div>
  <div class="row">
    <div class="col-md-12">
      <p><strong><%= t('.date') %></strong>
      <%= @juridico_processo.date.to_date.strftime("%d/%m/%Y") %></p>
      <p><%= @juridico_processo.shire %> - <%= @juridico_processo.circuit %></p>
    </div>
  </div>
  <div class="row">
    <div class="col-md-12">
      <p><strong><%= t('.judge') %></strong><%= @juridico_processo.judge %></p>
    </div>
  </div>
  <div class="row">
    <div class="col-md-12">
      <p><strong><%= t('.value') %></strong>
        <%= @juridico_processo.value %></p>
    </div>
  </div>
  <hr>
  <div class="row">
    <div class="col-md-12">
      <h4><strong><%= t('.process_parts') %></strong></h4>
    </div>
    <div class="col-md-6">
      <p><strong><%= t('.author') %></strong>
      <%= @juridico_processo.author %></p>
    </div>
    <div class="col-md-6">
      <p><strong><%= t('.defendant') %></strong>
      <%= @juridico_processo.defendant %></p>
    </div>
  </div>

  <hr>
  <div class="row">
    <div class="col-md-12">
      <h4><strong><%= t('.notes') %></strong></h4>
    </div>
    <div class="col-md-12">
      <p><%= @juridico_processo.notes %></p>
    </div>
  </div>
</section>
<hr>
<section id="notes">
  <div class="row">
    <div class="col-md-12"><h4><strong><%= t('.andamento') %></strong></h4></div>
  </div>
  <% if @juridico_processo.andamentos.any? %>
      <% @juridico_processo.andamentos.each do |andamento| %>
          <div class="row">
            <div class="col-md-2"><%= andamento.data.to_date.strftime("%d/%m/%Y") %></div>
            <div class="col-md-10"><%= andamento.nota %></div>
          </div>
      <% end %>
  <% else %>
      <div class="row">
        <div class="col-md-12"><p><%= I18n.t('Contact.view.no_registred', entitie: t('Contact.model.Phone')) %></p></div>
      </div>
  <% end %>

  <hr>
</section>



<div class="hidden-print">
<%= link_to t('.edit'), edit_juridico_processo_path(@juridico_processo) %> |
<%= link_to t('.back'), juridico_processos_path %>
</div>